# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: wardnath/reader

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v4
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
   
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
  
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo generating artifact...
          mkdir _archive
      - name: Create a file
        run: tar -cvf _archive/wardnath_reader.tar .
    
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wardnath_devbox_config
          path: _archive/wardnath_reader.tar
          retention-days: 30
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          # Artifact name
          name: wardnath_reader
          # Path of the directory containing the static assets.
          path: _archive
          # Duration after which artifact will expire in days.
          retention-days: 30
          # Steps represent a sequence of tasks that will be executed as part of the job
      - name: Dev Container Build and Run Action
        uses: devcontainers/ci@v0.3.1900000328
        with:
          imageName: ghcr.io/wardnath/reader
          cacheFrom: ghcr.io/wardnath/reader
          push: always
